require 'nokogiri'
require 'open-uri'
require 'pry'

require_relative '../lib/thanksgiving_recipes/version'
require_relative '../lib/thanksgiving_recipes/ingredient'
require_relative '../lib/thanksgiving_recipes/scraper'
require_relative '../lib/thanksgiving_recipes/recipe'
require_relative '../lib/thanksgiving_recipes/foodnetworkscraper'
require_relative '../lib/thanksgiving_recipes/cli'